name: Source tests CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.js'
  pull_request:
    branches: [ main ]
    paths:
      - '**.js'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Check for changes in index.js
      id: file-check
      uses: dorny/paths-filter@v2
      with:
        filters: |
          index:
            - 'index.js'
    - name: Run tests if index.js was changed
      if: steps.file-check.outputs.index
      run: yarn test
